const data = [
  { id: 701, word: "sore", choices: ["正確な", "海の", "痛い", "軍隊の"], correct: 2, sentence: "After climbing the mountain, my legs felt really sore the next day.", jp: "山に登った後，翌日は足が本当に痛かった。" },
  { id: 702, word: "permanently", choices: ["おおよそ", "正確に", "なんとかして", "永久に"], correct: 3, sentence: "He has decided to move to Japan permanently.", jp: "彼は日本に永住することを決めた。" },
  { id: 703, word: "antibiotic", choices: ["点", "筋", "抗生物質", "話"], correct: 2, sentence: "The doctor gave him some antibiotics.", jp: "医者は彼に抗生物質を投与した。" },
  { id: 704, word: "prescription", choices: ["商品", "物", "枠", "処方"], correct: 3, sentence: "The doctor gave me a prescription for some medicine for my headaches.", jp: "その医師は頭痛の薬の処方箋をくれた。" },
  { id: 705, word: "widespread", choices: ["広範囲にわたる", "痛い", "混成の", "激しい"], correct: 0, sentence: "The typhoon caused widespread damage.", jp: "その台風は広範囲にわたる被害をもたらした。" },
  { id: 706, word: "myth", choices: ["火山", "種類", "神話", "戸棚"], correct: 2, sentence: "A common myth is that people use only 10% of their brain.", jp: "よくある俗説に，人は脳の10％しか使っていないというものがある。" },
  { id: 707, word: "fiction", choices: ["作り話", "大学", "組織", "神話"], correct: 0, sentence: "Most people read less fiction as they get older.", jp: "ほとんどの人は，年を取るにつれて小説を読まなくなる。" },
  { id: 708, word: "tale", choices: ["処方", "話", "情報", "暴力"], correct: 1, sentence: "Children from all countries love to hear fairy tales.", jp: "どの国の子供たちもおとぎ話を聞くのが大好きだ。" },
  { id: 709, word: "plot", choices: ["命令", "運動", "筋", "小屋"], correct: 2, sentence: "The plot of the movie was OK, but the visual effects were fantastic.", jp: "その映画の筋書きはまあまあだったが，視覚効果は素晴らしかった。" },
  { id: 710, word: "symptom", choices: ["手順", "範疇", "症状", "部分"], correct: 2, sentence: "The symptoms of influenza and COVID-19 are very similar.", jp: "インフルエンザと新型コロナウイルスの症状はよく似ている。" },
  { id: 711, word: "comfort", choices: ["飛行", "症状", "家庭", "快適さ"], correct: 3, sentence: "We tried to comfort the woman over the sad loss of her dog.", jp: "私たちは愛犬との悲しい別れを乗り越えられるようにその女性を慰めようとした。" },
  { id: 712, word: "closet", choices: ["地震", "空間", "機関", "戸棚"], correct: 3, sentence: "I put my clothes into the closet.", jp: "私は服をクローゼットにしまった。" },
  { id: 713, word: "cabinet", choices: ["崩壊", "部族", "所有", "戸棚"], correct: 3, sentence: "We keep all our glasses in a small cabinet on the wall.", jp: "グラスはすべて壁側の小さな戸棚にしまっている。" },
  { id: 714, word: "pack", choices: ["積む", "課す", "充てる", "詰める"], correct: 3, sentence: "I have packed my suitcase ready for my trip.", jp: "旅行のためにスーツケースに荷物を詰め込んだ。" },
  { id: 715, word: "possibly", choices: ["正確に", "ひょっとすると", "永久に", "おおよそ"], correct: 1, sentence: "Could you possibly help me complete this form?", jp: "よろしければこの書類の記入を手伝っていただけますか。" },
  { id: 716, word: "somehow", choices: ["正確に", "なんとかして", "ひょっとすると", "永久に"], correct: 1, sentence: "I have to get to the airport somehow.", jp: "どうにかして空港に行かなければならない。" },
  { id: 717, word: "declare", choices: ["詰める", "さらす", "宣言する", "変える"], correct: 2, sentence: "The president declared that the war was over.", jp: "大統領は戦争は終わったと宣言した。" },
  { id: 718, word: "announce", choices: ["刺激する", "発表する", "宣言する", "禁止する"], correct: 1, sentence: "The school announced that there would be a new principal next year.", jp: "学校は来年新しい校長が来ると発表した。" },
  { id: 719, word: "talented", choices: ["優れた", "才能ある", "国内の", "率直な"], correct: 1, sentence: "He is a very talented artist.", jp: "彼はとても才能のある芸術家だ。" },
  { id: 720, word: "superior", choices: ["神経の", "民族の", "敏感な", "優れた"], correct: 3, sentence: "These shoes are far superior to those in quality.", jp: "この靴はあの靴よりも品質がはるかに優れている。" },
  { id: 721, word: "straight", choices: ["視覚の", "まっすぐな", "感覚の", "理想的な"], correct: 1, sentence: "Draw a straight line between the two circles.", jp: "２つの円の間に直線を１本引いてください。" },
  { id: 722, word: "frank", choices: ["移動式の", "率直な", "具体的な", "才能ある"], correct: 1, sentence: "To be frank, I do not want to leave school.", jp: "率直に言うと，私は学校を辞めたくない。" },
  { id: 723, word: "aviation", choices: ["器官", "哲学", "絶滅", "飛行"], correct: 3, sentence: "I dream of being an aviation engineer and designing new aircraft.", jp: "私は航空技師になり，新しい飛行機を設計するのを夢見ている。" },
  { id: 724, word: "lab", choices: ["冷蔵庫", "実験室", "器具", "作り話"], correct: 1, sentence: "Our college has special labs for the science majors.", jp: "私たちの大学には科学専攻学生のための特別な研究室がある。" },
  { id: 725, word: "institute", choices: ["実験室", "大学", "混合物", "薄切り"], correct: 1, sentence: "Our research institute is funded by the government.", jp: "私たちの研究所は政府から資金援助を受けている。" },
  { id: 726, word: "institution", choices: ["ダース", "代わり", "快適さ", "機関"], correct: 3, sentence: "He works for an educational institution which helps children with learning difficulties.", jp: "彼は学習困難な子供たちを支援する教育機関で働いている。" },
  { id: 727, word: "spot", choices: ["手がかり", "筋", "抗生物質", "点"], correct: 3, sentence: "He spotted the bird easily among the trees.", jp: "彼は木々の間から簡単にその鳥を見つけた。" },
  { id: 728, word: "dash", choices: ["噴火する", "衝突する", "急いで行く", "飛び出る"], correct: 2, sentence: "He dashed across the street to join his friends.", jp: "彼は友人と合流しようと通りを急いで横切った。" },
  { id: 729, word: "ethnic", choices: ["感謝している", "民族の", "まっすぐな", "非常に優れた"], correct: 1, sentence: "The mountains of northern Thailand are home to many ethnic groups.", jp: "タイ北部の山岳地帯には多くの民族集団が住んでいる。" },
  { id: 730, word: "tribe", choices: ["話", "枠", "点", "部族"], correct: 3, sentence: "I want to know more about the tribes of North America.", jp: "北アメリカの部族についてもっと知りたい。" },
  { id: 731, word: "precisely", choices: ["正確に", "ひょっとすると", "永久に", "なんとかして"], correct: 0, sentence: "I will meet you at precisely 12 o'clock.", jp: "12時ちょうどに会いましょう。" },
  { id: 732, word: "exact", choices: ["広範囲にわたる", "海の", "正確な", "痛い"], correct: 2, sentence: "We need the exact measurements.", jp: "正確な寸法が必要だ。" },
  { id: 733, word: "accurate", choices: ["優れた", "神経の", "正確な", "率直な"], correct: 2, sentence: "He made a fairly accurate map of the way to his home.", jp: "彼は自宅までの道のりのかなり正確な地図を作った。" },
  { id: 734, word: "military", choices: ["視覚の", "軍隊の", "感覚の", "敏感な"], correct: 1, sentence: "The United States has military bases in many countries.", jp: "アメリカは多くの国に軍隊の基地を持っている。" },
  { id: 735, word: "marine", choices: ["正確な", "海の", "激しい", "民族の"], correct: 1, sentence: "Global warming affects the habitats of marine animals.", jp: "地球温暖化は海洋動物の生息地に影響を与える。" },
  { id: 736, word: "endanger", choices: ["発表する", "再生する", "許可する", "危険にさらす"], correct: 3, sentence: "Man's actions have endangered many species of animals.", jp: "人間の行為が多くの動物種を絶滅の危機にさらしている。" },
  { id: 737, word: "fierce", choices: ["国内の", "激しい", "混成の", "軍隊の"], correct: 1, sentence: "Reports say that there is fierce fighting occurring near the government offices.", jp: "報道によると官庁の近くで激しい戦闘が起きている。" },
  { id: 738, word: "earthquake", choices: ["症状", "崩壊", "地震", "物"], correct: 2, sentence: "This area had another earthquake last night.", jp: "この地域では昨夜もまた地震があった。" },
  { id: 739, word: "volcano", choices: ["器具", "火山", "商品", "範疇"], correct: 1, sentence: "Mauna Loa is one of the largest active volcanoes in the world.", jp: "マウナ・ロアは世界最大の活火山の１つだ。" },
  { id: 740, word: "erupt", choices: ["急いで行く", "衝突する", "噴火する", "飛び出る"], correct: 2, sentence: "A volcano in Iceland has erupted again this morning.", jp: "今朝，アイスランドの火山が再び噴火した。" },
  { id: 741, word: "collapse", choices: ["情報", "崩壊", "命令", "大学"], correct: 1, sentence: "Many buildings collapsed in the earthquake.", jp: "この地震で多くの建物が倒壊した。" },
  { id: 742, word: "extinction", choices: ["絶滅", "地震", "暴力", "哲学"], correct: 0, sentence: "Climate change is causing the extinction of many kinds of animals.", jp: "気候変動は多くの種類の動物の絶滅を引き起こしている。" },
  { id: 743, word: "chamber", choices: ["小屋", "手順", "空間", "家庭"], correct: 2, sentence: "The heart consists of four chambers.", jp: "心臓は４つの小室で構成されている。" },
  { id: 744, word: "cabin", choices: ["所有", "器官", "小屋", "戸棚"], correct: 2, sentence: "We stayed at a log cabin that night.", jp: "私たちはその夜，丸太小屋に泊まった。" },
  { id: 745, word: "visual", choices: ["視覚の", "具体的な", "理想的な", "移動式の"], correct: 0, sentence: "The Internet provides us with many visual images of the world.", jp: "インターネットは私たちに世界の多くの視覚映像を与えてくれる。" },
  { id: 746, word: "motion", choices: ["絶滅", "機関", "神話", "運動"], correct: 3, sentence: "He made some quick motions with his hands.", jp: "彼は両手で素早い動きをした。" },
  { id: 747, word: "frame", choices: ["枠", "部分", "火山", "運動"], correct: 0, sentence: "He put his painting in a beautiful frame.", jp: "彼は絵を美しい額に入れた。" },
  { id: 748, word: "crash", choices: ["急いで行く", "飛び出る", "衝突する", "噴火する"], correct: 2, sentence: "The car crashed into the wall of the house.", jp: "車は家の壁に衝突した。" },
  { id: 749, word: "trigger", choices: ["検知する", "のきっかけになる", "飲み込む", "移植する"], correct: 1, sentence: "The pollen from cedar trees can trigger an allergic reaction in many people.", jp: "杉の木の花粉は多くの人にアレルギー反応を引き起こす可能性がある。" },
  { id: 750, word: "clue", choices: ["飛行", "処方", "手がかり", "空間"], correct: 2, sentence: "By adding all the clues together you can solve the puzzle.", jp: "すべてのヒントを足し合わせるとパズルが解ける。" },
  { id: 751, word: "organ", choices: ["種類", "器官", "部族", "組織"], correct: 1, sentence: "I decided to become an organ donor when I die.", jp: "私は死んだら臓器提供者になろうと決めた。" },
  { id: 752, word: "tissue", choices: ["作り話", "実験室", "快適さ", "組織"], correct: 3, sentence: "Skin tissue does not completely heal after a serious burn.", jp: "大やけどの後，皮膚組織は完全には治らない。" },
  { id: 753, word: "transplant", choices: ["かき混ぜる", "危険にさらす", "のよさを認める", "移植する"], correct: 3, sentence: "My uncle had a heart transplant last year.", jp: "私のおじは昨年心臓移植を受けた。" },
  { id: 754, word: "dozen", choices: ["混合物", "薄切り", "代わり", "ダース"], correct: 3, sentence: "I bought half a dozen apples at the store.", jp: "私は店で半ダースのリンゴを買った。" },
  { id: 755, word: "load", choices: ["積む", "のきっかけになる", "充てる", "課す"], correct: 0, sentence: "We loaded all our furniture onto the truck.", jp: "私たちはトラックにすべての家具を積み込んだ。" },
  { id: 756, word: "compound", choices: ["ダース", "手がかり", "混合物", "冷蔵庫"], correct: 2, sentence: "Scientists are continually finding new chemical compounds.", jp: "科学者たちは絶えず新しい化合物を発見している。" },
  { id: 757, word: "hybrid", choices: ["非常に優れた", "まっすぐな", "混成の", "才能ある"], correct: 2, sentence: "The new government campaign encourages people to buy hybrid cars.", jp: "新しい政府のキャンペーンは人々にハイブリッド車の購入を奨励している。" },
  { id: 758, word: "permit", choices: ["積む", "さらす", "許可する", "詰める"], correct: 2, sentence: "Smoking is not permitted in this building.", jp: "この建物では喫煙は許可されていない。" },
  { id: 759, word: "ban", choices: ["刺激する", "禁止する", "変える", "移植する"], correct: 1, sentence: "The school tried to ban smartphones in the classroom.", jp: "学校は教室でのスマートフォンを禁止しようとした。" },
  { id: 760, word: "prohibit", choices: ["検知する", "発表する", "禁止する", "宣言する"], correct: 2, sentence: "Bringing dairy or meat products into the country is prohibited.", jp: "その国への乳製品や肉製品の持ち込みは禁止されている。" },
  { id: 761, word: "excellent", choices: ["感謝している", "海の", "広範囲にわたる", "非常に優れた"], correct: 3, sentence: "I got excellent grades in my end-of-year tests.", jp: "私は学年末テストで非常に優れた成績をとった。" },
  { id: 762, word: "detect", choices: ["検知する", "禁止する", "再生する", "飲み込む"], correct: 0, sentence: "The earthquake was so small that it was difficult to detect.", jp: "その地震はとても小さかったので，感知するのは難しかった。" },
  { id: 763, word: "expose", choices: ["危険にさらす", "さらす", "かき混ぜる", "許可する"], correct: 1, sentence: "The garden is exposed to the sun all day.", jp: "庭は一日中日光にさらされている。" },
  { id: 764, word: "sensitive", choices: ["痛い", "神経の", "正確な", "敏感な"], correct: 3, sentence: "I have very sensitive skin, so I must be careful on sunny days.", jp: "私は肌がとても敏感なので，晴れの日には気をつけなければならない。" },
  { id: 765, word: "roughly", choices: ["おおよそ", "ひょっとすると", "なんとかして", "永久に"], correct: 0, sentence: "It will take me roughly two hours to finish the job.", jp: "その仕事を終えるのにおおよそ2時間かかるだろう。" },
  { id: 766, word: "approximately", choices: ["おおよそ", "ひょっとすると", "正確に", "なんとかして"], correct: 0, sentence: "There were approximately 25 people at the meeting.", jp: "ミーティングには約25人が参加した。" },
  { id: 767, word: "nervous", choices: ["国内の", "神経の", "感覚の", "軍隊の"], correct: 1, sentence: "He was feeling nervous before the important job interview.", jp: "彼は大事な採用面接を前に緊張していた。" },
  { id: 768, word: "devote", choices: ["のきっかけになる", "積む", "のよさを認める", "充てる"], correct: 3, sentence: "Since he stopped working, he has devoted his time to his hobbies.", jp: "仕事をやめてから，彼は趣味に時間を注いでいる。" },
  { id: 769, word: "procedure", choices: ["筋", "手順", "抗生物質", "枠"], correct: 1, sentence: "Please follow the official procedure to apply for the position.", jp: "正式な手続きに従ってその職に応募してください。" },
  { id: 770, word: "sensory", choices: ["混成の", "優れた", "感覚の", "民族の"], correct: 2, sentence: "I am interested in how the brain processes sensory information.", jp: "私は脳がどのように感覚情報を処理するかに興味がある。" },
  { id: 771, word: "data", choices: ["点", "物", "情報", "話"], correct: 2, sentence: "We need a powerful computer to analyze all this data.", jp: "このデータをすべて分析するには，高性能なコンピューターが必要だ。" },
  { id: 772, word: "command", choices: ["絶滅", "崩壊", "命令", "小屋"], correct: 2, sentence: "The scientist gave the robot some commands to complete simple tasks.", jp: "科学者はロボットに簡単な仕事を完了させる命令を出した。" },
  { id: 773, word: "ideal", choices: ["敏感な", "激しい", "理想的な", "率直な"], correct: 2, sentence: "The park is an ideal place for families with small children to visit.", jp: "その公園は小さな子供連れの家族が訪れるのに理想的な場所だ。" },
  { id: 774, word: "reproduce", choices: ["再生する", "課す", "充てる", "変える"], correct: 0, sentence: "All creatures have found a way to reproduce in order to survive.", jp: "すべての生き物は，生き残るために繁殖する方法を見つけてきた。" },
  { id: 775, word: "impose", choices: ["さらす", "詰める", "禁止する", "課す"], correct: 3, sentence: "The local government imposes a fine on anybody who smokes on the street.", jp: "その地方自治体はすべての路上喫煙者に罰金を課している。" },
  { id: 776, word: "violence", choices: ["暴力", "器具", "処方", "大学"], correct: 0, sentence: "The number of cases of domestic violence has gradually decreased in that country.", jp: "その国では家庭内暴力事件の件数は徐々に減少している。" },
  { id: 777, word: "mobile", choices: ["視覚の", "理想的な", "移動式の", "具体的な"], correct: 2, sentence: "Many parents let their small child play on a mobile device.", jp: "多くの親が小さな子供を携帯端末で遊ばせている。" },
  { id: 778, word: "chip", choices: ["地震", "空間", "戸棚", "薄切り"], correct: 3, sentence: "I really love chocolate chip cookies.", jp: "私はチョコレートチップクッキーが大好きだ。" },
  { id: 779, word: "portion", choices: ["運動", "機関", "神話", "部分"], correct: 3, sentence: "He divided the cake into equal portions.", jp: "彼はケーキを等しい分け前になるように分けた。" },
  { id: 780, word: "alter", choices: ["飲み込む", "許可する", "検知する", "変える"], correct: 3, sentence: "She altered the photograph slightly using her computer.", jp: "彼女はパソコンで写真を少し変えた。" },
  { id: 781, word: "alternative", choices: ["器官", "代わり", "暴力", "症状"], correct: 1, sentence: "We had no alternative but to sell the house.", jp: "私たちは家を売る以外の選択肢がなかった。" },
  { id: 782, word: "appreciate", choices: ["発表する", "のよさを認める", "再生する", "移植する"], correct: 1, sentence: "I appreciate all the help that you have given me.", jp: "あなたの助けのすべてに感謝しています。" },
  { id: 783, word: "grateful", choices: ["まっすぐな", "感謝している", "才能ある", "移動式の"], correct: 1, sentence: "I am really grateful that you offered to help me move house.", jp: "引っ越しの手伝いを申し出てくれて本当に感謝している。" },
  { id: 784, word: "philosophy", choices: ["範疇", "家庭", "哲学", "情報"], correct: 2, sentence: "Much of European philosophy is based on the ideas of the ancient Greeks.", jp: "ヨーロッパの哲学の多くは古代ギリシャの思想に基づいている。" },
  { id: 785, word: "pop", choices: ["噴火する", "飛び出る", "急いで行く", "衝突する"], correct: 1, sentence: "A picture popped up when I clicked the link.", jp: "そのリンクをクリックすると写真が飛び出してきた。" },
  { id: 786, word: "domestic", choices: ["非常に優れた", "感謝している", "国内の", "広範囲にわたる"], correct: 2, sentence: "Domestic tourists are still the main source of income for many areas of Japan.", jp: "日本の多くの地域にとって，国内観光客はいまだに主な収入源である。" },
  { id: 787, word: "household", choices: ["命令", "飛行", "部分", "家庭"], correct: 3, sentence: "The new law aims to aid low-income households.", jp: "その新しい法律は低所得世帯の支援を目的としている。" },
  { id: 788, word: "appliance", choices: ["部族", "哲学", "所有", "器具"], correct: 3, sentence: "The price of household appliances has gone up recently.", jp: "最近家電製品の値段が上がっている。" },
  { id: 789, word: "refrigerator", choices: ["商品", "手順", "冷蔵庫", "種類"], correct: 2, sentence: "Please put tomatoes in the refrigerator.", jp: "トマトは冷蔵庫に入れてください。" },
  { id: 790, word: "sort", choices: ["快適さ", "組織", "火山", "種類"], correct: 3, sentence: "What sort of job are you looking for?", jp: "どのような種類の仕事をお探しですか。" },
  { id: 791, word: "concrete", choices: ["正確な", "具体的な", "痛い", "海の"], correct: 1, sentence: "The police have no concrete evidence that he committed the crime.", jp: "警察は彼が犯罪を犯したという具体的な証拠を持っていない。" },
  { id: 792, word: "category", choices: ["実験室", "範疇", "混合物", "薄切り"], correct: 1, sentence: "We divided the books into different categories.", jp: "我々は本をさまざまな部類に分けた。" },
  { id: 793, word: "stuff", choices: ["作り話", "物", "代わり", "ダース"], correct: 1, sentence: "My room has a lot of stuff that I want to throw away.", jp: "私の部屋には捨てたいものがたくさんある。" },
  { id: 794, word: "stimulate", choices: ["宣言する", "刺激する", "かき混ぜる", "危険にさらす"], correct: 1, sentence: "The smells from the kitchen stimulated my appetite.", jp: "台所からの匂いが食欲を刺激した。" },
  { id: 795, word: "stir", choices: ["のきっかけになる", "のよさを認める", "かき混ぜる", "刺激する"], correct: 2, sentence: "It is a powerful movie that really stirs the emotions.", jp: "それは本当に感情をかき立てる力強い映画だ。" },
  { id: 796, word: "goods", choices: ["手がかり", "冷蔵庫", "商品", "抗生物質"], correct: 2, sentence: "We sell various types of electronic goods to overseas customers.", jp: "私たちは海外の顧客にさまざまな種類の電子製品を販売している。" },
  { id: 797, word: "swallow", choices: ["詰める", "課す", "飲み込む", "積む"], correct: 2, sentence: "I always find it difficult to swallow medicine.", jp: "私はいつも薬を飲み込むのが難しいと思う。" },
  { id: 798, word: "possession", choices: ["点", "物", "筋", "所有"], correct: 3, sentence: "I try to keep my valuable possessions in a safe place.", jp: "貴重品は安全な場所に保管するようにしている。" },
  { id: 799, word: "whereas", choices: ["一方で", "することは何でも", "おおよそ", "話"], correct: 0, sentence: "I am a morning person, whereas my brother is a night owl.", jp: "私は朝型ですが，兄は夜型です。" },
  { id: 800, word: "whatever", choices: ["枠", "することは何でも", "一方で", "部分"], correct: 1, sentence: "You can do whatever you want.", jp: "あなたが望むことは何でもできます。" },
];